/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SOLENOID_PB_H_INCLUDED
#define PB_SOLENOID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Solenoid {
    int32_t id;
    int32_t time;
} Solenoid;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Solenoid_init_default                    {0, 0}
#define Solenoid_init_zero                       {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Solenoid_id_tag                          1
#define Solenoid_time_tag                        2

/* Struct field encoding specification for nanopb */
#define Solenoid_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, INT32,    time,              2)
#define Solenoid_CALLBACK NULL
#define Solenoid_DEFAULT NULL

extern const pb_msgdesc_t Solenoid_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Solenoid_fields &Solenoid_msg

/* Maximum encoded size of messages (where known) */
#define SOLENOID_PB_H_MAX_SIZE                   Solenoid_size
#define Solenoid_size                            22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
